### ISSUE TITLE
[bug] route resource provisioner doesn't support environment variable param

### ISSUE THREAD

**Issue by astromechza** [score-spec/score-compose#106]
```
...
resources:
  env:
    type: environment
  route:
    type: route
    params:
      host: ${resources.env.EXTERNAL_HOSTNAME}
      port: web
      path: /
```

This throws an error like 

```
Error: failed to provision: resource 'route.default#example.route': failed to provision: init template failed: failed to execute template: template: :4:64: executing "" at <fail "params.host must be a valid hostname">: error calling fail: params.host must be a valid hostname
```

Because params.host becomes `${EXTERNAL_HOSTNAME}`.

We may need to adjust this so that env references actually resolve to their real values (or fail) when resolved in a resource param.
