### ISSUE TITLE
`service` resource type not supported

### ISSUE THREAD

**Issue by mathieu-benoit** [score-spec/score-compose#118]
I have this `score.file`:
```yaml
apiVersion: score.dev/v1b1
metadata:
  name: store-front
containers:
  store-front:
    image: .
    variables:
      VUE_APP_ORDER_SERVICE_URL: "http://${resources.order-service.name}:3000/"
resources:
  order-service:
    type: service
```
But I'm getting this error while running `score-compose generate`:
```
Error: failed to provision: resource 'service.default#store-front.order-service' is not supported by any provisioner
```
I understand that [`service-port`](https://github.com/score-spec/score-compose/issues/87#issuecomment-2014967881) has been supported only for `score-compose`? But how to make sure that I have the same Score file compatible with `score-compose` and Humanitec?

**Comment by mathieu-benoit** [comment]
In the meantime, like discussed with @astromechza, we could add a custom provisioner to support this:
```yaml
- uri: template://static-service
  type: service
  outputs: |
    name: <hostname>
```

**Comment by mathieu-benoit** [comment]
This below is working:
```yaml
- uri: template://service-provisioners/static-service
  type: service
  init: |
    name: {{ splitList "." .Id | last }}
  outputs: |
    {{ $w := (index .WorkloadServices .Init.name) }}
    name: {{ $w.ServiceName | quote }}
```

@astromechza, should we have this upstream in the `default-provisioners`?

**Comment by astromechza** [comment]
@mathieu-benoit what is the definition of a "service"? does it just return a random hostname? What gets provisioned when we declare it?

The problem with the generic `service` is that we need to "match" it to a specific workload by name and convert that to the dns name for the workload. Then the port is more complicated because in score-compose we don't have a kube-proxy like in kubernetes so we can't use the service port, we have to translate the service port to a container port.

So in your example above, if the order service has:

```
service:
  ports:
    web:
      port: 3000
      targetPort: 9000
```

We need to actually translate your port 3000, into port 9000. This is why the "service port" exists in score-compose. In Humanitec, it targets Kubernetes, so it can use the port of the service, although no validation is done to check if the service actually has port 3000 declared.

(I'm converting this ticket to a feature request)
