### ISSUE TITLE
Services port protocol does not translate well to compose

### ISSUE THREAD

**Issue by fernando-villalba** [score-spec/score-compose#146]
If I do the following:
```yaml
apiVersion: score.dev/v1b1
metadata:
  name: frontend
containers:
  frontend:
    image: nginx:alpine
service:
  ports:
    www:
      port: 80
      protocol: TCP
      targetPort: 80
```

It translates to helm values correctly like so:
```yaml
containers:
  frontend:
    image:
      name: nginx:alpine
service:
  ports:
    - name: www
      port: 80
      protocol: TCP
      targetPort: 80
  type: ClusterIP
```

How it does not translate correctly to compose:

```yaml
services:
  frontend:
    image: nginx:alpine
    ports:
      - target: 80
        published: "80"
        protocol: TCP
```

Becuase in compose the protocol needs to be specified in lower case, otherwise it fails.
