### ISSUE TITLE
[FEATURE] support volume subpath

### ISSUE THREAD

**Issue by ndeloof** [score-spec/score-compose#166]
Documentation says:

> Volume mounts with path will be rejected. Docker compose doesn't support sub-path mounts for Docker volumes."

this isn't true (since https://github.com/compose-spec/compose-go/pull/594)
```yaml
      - type: volume
        source: foo
        target: /app
        volume:
          subpath: etc/settings
```
