### ISSUE TITLE
[feature request] Add a default `mssql` provisioner

### ISSUE THREAD

**Issue by mathieu-benoit** [score-spec/score-compose#195]
Let's add a default `mssql` provisioner, with `outputs`:
- `connection`

For references:
- https://learn.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker
- https://mcr.microsoft.com/artifact/mar/mssql/server/about

A basic compose file to take inspiration from, could be something around this:
```
version: '3.8'
services:
  sql-server:
    image: mcr.microsoft.com/mssql/server
    container_name: sql-server-container
    environment:
      SA_PASSWORD: <your_password_here>
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
```

Need to be tested and adapted, source file: https://github.com/score-spec/score-compose/blob/main/internal/command/default.provisioners.yaml.
