### ISSUE TITLE
[feature request] Add a new `score-compose provisioners list` command

### ISSUE THREAD

**Issue by mathieu-benoit** [score-spec/score-compose#237]
Add a new `score-compose provisioners list` command generating in the output this table or a more advanced/detailed version with `-o json`: https://docs.score.dev/docs/score-implementation/score-compose/resources-provisioners/.

- It's not something in `score-go` as it's specific to each implementation.
- This should list the overriden `provisioners` imported via the `score-compose init --provisioners` command

**Comment by astromechza** [comment]
Can I rather recommend we use `score-compose provisioners list` instead and look at moving the --provisioners flag over to `score-compose provisioners add` in future?

**Comment by lekaf974** [comment]
@mathieu-benoit description of issue is still mentioning `--provisioners`

**Comment by lekaf974** [comment]
@mathieu-benoit I could give it a try

**Comment by mathieu-benoit** [comment]
That would be awesome! If you have any questions while implementing this, please do let us know. There is a #score-dev channel in the CNCF Slack for this purpose.

**Comment by lekaf974** [comment]
Have a question related to array to display, currently after running `score-compose init --provisioners <rprovisioners source> --project <project name>` I am seeing the Z-xxx.xxxx.provisioners.yaml is created.
The array have 4 headers type, class, params, output

From this file I can easily extract type and output, I see that params will need a little more work but nothing reallay hard. Finally it is for the class header I am not sure where it is defined and I did not found any documentation that describe this field. Could you give me some guidance here ?

**Comment by mathieu-benoit** [comment]
Good question, it's not yet well documented for this part, I'll add a note to this one https://github.com/score-spec/docs/issues/121 to make sure we'll document this properly.

In the meantime, here is the tl,dr about `class`:
- The default `class` if ommited in the `provisioner` is `default`.
- You can have multiple provisioners with the same `type` if their `class` is different. Example: `dns` with `class: internal` or `class: public`, etc. Example here with `dapr-state-store`: https://github.com/score-spec/community-provisioners/blob/main/score-compose/00-redis-dapr-state-store.provisioners.yaml#L3C3-L3C15.
- `class` can be used like illustrated below in the Score file, good way for the PEs to expose well supported golden paths and for the  Devs to provide more context around their request: "I want a public DNS".
- All the default `provisioners` coming with `score-compose init` don't have a `class` defined, meaning `default`: https://docs.score.dev/docs/score-implementation/score-compose/resources-provisioners/
- You can also query the list of resours like this: `score-compose resources get-outputs dns.default#my-workload.dns` (`default` being the `class`).

```
apiVersion: score.dev/v1b1
metadata:
  name: my-workload
containers:
  my-container:
    image: .
resources:
  dns:
    type: dns
    class: public # optional, default if omitted
  route:
    type: route
    params:
      host: ${resources.dns.host}
      path: /
      port: 8080
service:
  ports:
    tcp:
      port: 8080
      targetPort: 8080
```

Hope this helps for more context?
