### ISSUE TITLE
[bug] Only one workload is included in compose output

### ISSUE THREAD

**Issue by williamoverton** [score-spec/score-compose#26]
**Describe the bug**
If I have a score.yaml file which defines two workloads, only one workload is included in the output of `score-compose`

**To Reproduce**
1. Create a score.yaml file like the following:
```yaml
apiVersion: score.dev/v1b1

metadata:
  name: app

service:
  ports:
    api:
      port: 80
      targetPort: 3000
    frontend:
      port: 8080
      targetPort: 3000

containers:
  api:
    image: api:latest
  frontend:
    image: frontend:latest
```

2. run `score-compose`:
``` $ score-compose run
services:
  app:
    image: frontend:latest
    ports:
      - target: 3000
        published: "80"
      - target: 3000
        published: "8080"
```

**Expected behavior**
Both containers should be created and ports should be applied to the correct container.
`score-helm` seems to work correctly:
``` $ score-helm run                       
containers:
  api:
    image:
      name: api:latest
  frontend:
    image:
      name: frontend:latest
service:
  ports:
    - name: api
      port: 80
      targetPort: 3000
    - name: frontend
      port: 8080
      targetPort: 3000
  type: ClusterIP
```

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.0
 - Version: score-compose 0.1.0 (build: 2022-10-17T09:17:36Z; sha: ef20200fa8357ef8dbffbed38f3de53ebdc2d9c2)
