### ISSUE TITLE
[bug] score-compose is not correctly handling multiple containers in the same service definition

### ISSUE THREAD

**Issue by queirozmarcus** [score-spec/score-compose#42]
**Describe the bug**
You can see that score-compose is not correctly handling multiple containers in the same service definition.

**How to reproduce**
This issue can be reproduced by triggering score-comppose. For example:
run score-compose run -f ./score.yaml -o ./compose.yaml with the following score.yaml file:

```
apiVersion: score.dev/v1b1
metadata:
  name: score-setup

service:
  ports:
    db:
      port: 3306
      targetPort: 3306
    api:
      port: 8080
      targetPort: 8080

containers:
  db-mysql:
    image: mysql:latest
    variables:
      MYSQL_ROOT_PASSWORD: root
    
  api-service:
    image: api:latest
    variables:
      JAVA_TOOL_OPTIONS: "-Dfile.encoding=UTF8"
```
You can see that score-compose is not correctly handling multiple containers in the same service definition.

**Actual behaviour**
The score-compose output is limited to a single container. And after a few runs with score-compose the output alternates between containers. 

```
$ score-compose run -f score.yaml -o compose.yaml
services:
  score-setup:
    environment:
      JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
    image: api:latest
    ports:
      - target: 3306
        published: "3306"
      - target: 8080
        published: "8080"

```

**Expected behavior**
I anticipate that the output should accurately reflect all the containers declared in the score.yaml file and represent them appropriately in the compose.yaml.

```
version: '3.8'

services:
  db-mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  api-service:
    image: api:latest
    environment:
      JAVA_TOOL_OPTIONS: "-Dfile.encoding=UTF8"
    ports:
      - "8080:8080"
```

**Desktop (please complete the following information):**
 - OS: Linux - Ubuntu
 - Version: score-compose_0.6.0_linux_amd64.

**Comment by sujaya-sys** [comment]
Hi @queirozmarcus we only support single container workloads in `score-compose` today. This ensures that we  generate a service that has the same name as the workload - which is why we're not allowing for two or more different images in a single service. 

@ghen might be able to provide further context on potential workarounds. My suggestion would be to turn this into a feature request. Would it be worth discussing the option of using the container name for the compose service name instead?

**Comment by ghen** [comment]
If we create one service per container with compose, this would bring other complications:
* Other CLI tools are create one service per workload (e.g. `score-helm`, `score-humanitec`). Generally user expect that the workload can combine more than one container that would share the environment and the network interface allocated to the workload/service by the host engine. This might not be the case with multiple compose services.
* If someone would try to spin-up two workloads via `score-compose`, and those are using clashing container names, this would lead to undesired result for the user without any warnings. Compose would simply use the latest service definition.
* Several settings in score that relate to the workload, such as a external ports mappings, can't be duplicated for each container.

Implementing such change require detailed investigation for all these and other common use cases.

**Comment by lornebp** [comment]
Just wondering if a feature request was ever raised for this issue and if so what the status was? We've just started working with Score and had a similar expectation of score-compose's output as @queirozmarcus had. 

@queirozmarcus did you manage to get this working as expected somehow?

**Comment by bobbydeveaux** [comment]
Don't 99% of docker-compose files have more than 1 service? I don't understand how using score really meets its goal, "Score aims to improve developer productivity and experience by reducing the risk of configuration inconsistencies between local and remote environments." without the basic requirement of score-compose supporting multiple services? Unless I'm mistaken?

**Comment by sujaya-sys** [comment]
Thanks for bringing this issue to our attention! A few notes:
- We will look into `score-compose` supporting more than one container per workload. As all of you mentioned is this an absolute valid and common use case.
- Its important to note though that the example referenced in this issue is to be resolved in a different way: The `db-mysql` shouldn’t be defined as a container but rather as a [resource dependency](https://docs.score.dev/docs/dependencies/) to avoid unexpected behaviour with other Score implementation CLIs. That being said, this is helpful input for the [project melody](https://score.dev/blog/project-melody) initiative we're currently looking into. We're focusing on making resource management in score-compose easier to understand / implement - and aim to support users with structuring their Score files as intended.

**For reference:**

```
containers:
  db-mysql:
    image: mysql:latest
    variables:
      MYSQL_ROOT_PASSWORD: root
    
  api-service:
    image: api:latest
    variables:
      JAVA_TOOL_OPTIONS: "-Dfile.encoding=UTF8"
```
