### ISSUE TITLE
[bug] does not generate depends_on

### ISSUE THREAD

**Issue by naruse666** [score-spec/score-compose#43]
**Describe the bug**
I'm looking at Set dependent Workloads.
https://docs.score.dev/docs/dependencies/#example-with-score-compose

```sh
score-compose run -f ./service-b.yaml -o ./service-b.compose.yaml
score-compose run -f ./service-a.yaml -o ./service-a.compose.yaml --env-file ./.env
```
The file generated by this command does not contain depends_on.

This is what was actually generated.
```yaml
services:
  service-a:
    command:
      - -c
      - 'while true; do echo service-a: Hello $${FRIEND}! Connecting to ${CONNECTION_STRING}...; sleep 10; done'
    entrypoint:
      - /bin/sh
    environment:
      CONNECTION_STRING: postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      FRIEND: ${NAME}
    image: busybox
```

**To Reproduce**
follow the documentation.

**Expected behavior**
generate depends_on.

**Desktop (please complete the following information):**
 - OS: macOS
 - Version Ventura 13.2.1

**score-compose version**
score-compose 0.8.0 (build: 2023-09-28T08:29:12Z; sha: 0eca45972a068de759930414fe0be96c87de2e97)
