### ISSUE TITLE
[bug] volume not generated

### ISSUE THREAD

**Issue by naruse666** [score-spec/score-compose#44]
**Describe the bug**
I defined a simple volume and generated `compose.yaml`.
But `compose.yaml` does not contain volumes.

***score.yaml***
```yaml 
apiVersion: score.dev/v1b1

metadata:
  name: hello-world
containers:
  awesome-web-service:
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo Hello!; sleep 100; done"]
    volumes:
    - source: ${resources.tmp-data}
      target: /tmp

resources:
  tmp-data:
    type: volume
```

***generate compose.yaml***
```sh
score-compose run -f score.yaml -o compose.yaml
```

***compose.yaml***
```yaml
services:
  hello-world:
    command:
      - -c
      - while true; do echo Hello!; sleep 100; done
    entrypoint:
      - /bin/sh
    image: busybox
    volumes:
      - type: volume
        source: tmp-data
        target: /tmp
```

**Expected behavior**
```yaml
services:
  hello-world:
    command:
      - -c
      - while true; do echo Hello!; sleep 100; done
    entrypoint:
      - /bin/sh
    image: busybox
    volumes:
      - type: volume
        source: tmp-data
        target: /tmp
volumes:       # generated this block
  tmp-data:    #
```

**Desktop (please complete the following information):**
 - OS: macOS
 - Version [e.g. 1.1.0]

**Additional context**
I'm a newbie to Score, so my thinking may be wrong.
