### ISSUE TITLE
[feature request] Add native support for `service` resource type

### ISSUE THREAD

**Issue by astromechza** [score-spec/score-compose#87]
When deploying 2 services in Score, such as a frontend and a backend you may need to pass a hostname:port reference from one to the other.

For example, the backend service may have a postgres database, and the frontend application may need an environment variable pointing to the service name and port of the backend.

```
apiVersion: score.dev/v1b1
metadata:
  name: backend
containers:
  main:
    image: my-backend
    ...
service:
  ports:
    web:
      port: 8080
resources:
  db:
    type: postgres
```

```
apiVersion: score.dev/v1b1
metadata:
  name: frontend
containers:
  main:
    image: my-frontend
    variables:
      BACKEND_SERVICE: http://${resources.backend.host}:${resources.backend.port}
    ...
resources:
  backend:
    type: service
    params:
      workload: backend
      port: web
```

This means that deploying the frontend must be done when the backend service has already been added to the score project.

```console
$ score-compose init
$ score-compose generate backend/score.yaml
$ score-compose generate frontend/score.yaml
```

This can be implemented as a provisioner in the default provisioners file.

Think about how/whether to enforce a service dependency on the backend service...
