### ISSUE TITLE
[feature request] implement env-file output for score-compose generate

### ISSUE THREAD

**Issue by astromechza** [score-spec/score-compose#90]
This would be the same as the env file output for the older score-compose run. 

It should spit out any env var's refered to by any `type: environment` resources.

eg: with the input

```
metadata:
  name: example
containers:
  thing:
    image: thing
    variables:
      KEY: ${resources.env.FOO}
      KEY2: ${resources.env.BAR}
```

and if we passed `--output-env-file .env`, we'd end up with a `.env` file in the current directory containing

```
FOO=
BAR=
```

And this would be automatically loadded by docker compose up at run time. 

The old implementation also embedded the current values, but I think this should be done manually, since the current values may contain secrets, and writing them to disk would not be good practise.
