### ISSUE TITLE
[bug] score-compose resolves inline files in the current working directory

### ISSUE THREAD

**Issue by astromechza** [score-spec/score-compose#95]
When the score spec contains container files with relative source paths, for example:

```
containers:
  foo:
    image: blah
    files:
    - source: ./some/file.txt
      target: /file.txt
```

The correct behavior should be that the path is resolved relative to the score file. So when you run `score-compose generate component/score.yaml`, the file should resolve to component/some/file.txt and not just ./some/file.txt. Since this makes multi-workload solutions complex and confusing.
